server:
  port: 8082
  servlet:
    context-path: /demo

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      master:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false&allowMultiQueries=true
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        validationQuery: select 1 from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        statementExecutableSqlLogEnable: true
      slave1:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false&allowMultiQueries=true
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        validationQuery: select 1 from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        statementExecutableSqlLogEnable: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nice.login.domain
  configuration:
    log-prefix: dao.
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  config: classpath:logback.xml
